# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('Choise1', models.TextField(verbose_name='choice1')),
                ('Choise2', models.TextField(verbose_name='choise2')),
                ('Choise3', models.TextField(verbose_name='choise3')),
                ('Choise4', models.TextField(verbose_name='choise4')),
                ('corrent_answer', models.CharField(max_length=10, verbose_name='correct answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('created_date', models.DateField(auto_now=True)),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
