# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
    ]
