# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_remove_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.IntegerField(default=2345235),
            preserve_default=False,
        ),
    ]
