# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20200317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
